-- Licensed to the Apache Software Foundation (ASF) under one or more
-- contributor license agreements.  See the NOTICE file distributed with
-- this work for additional information regarding copyright ownership.
-- The ASF licenses this file to You under the Apache License, Version 2.0
-- (the "License"); you may not use this file except in compliance with
-- the License.  You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

set mapred.job.tracker=localhost:9001;
set hive.metastore.warehouse.dir=hdfs://localhost:9000/user/hive/warehouse;

add jar file:///Users/amccurry/Development/incubator-blur/contrib/blur-hive/target/blur-hive-0.2.4-incubating-SNAPSHOT-hadoop1.jar;

create database if not exists test;
use test;

CREATE TABLE if not exists test  
ROW FORMAT SERDE 'org.apache.blur.hive.BlurSerDe'
WITH SERDEPROPERTIES (
  'blur.zookeeper.connection'='localhost',
  'blur.table'='test_hdfs',
  'blur.family'='fam0'
)
STORED BY 'org.apache.blur.hive.BlurHiveStorageHandler';

desc test;

create table if not exists input_data (
 rowid string,
 recordid string,
 col0 string,
 col1 string,
 col2 string,
 col3 string,
 col4 string,
 col5 string,
 col6 string,
 col7 string,
 col8 string,
 col9 string
);

select * from input_data;

insert table test select * from input_data;



