-- Licensed to the Apache Software Foundation (ASF) under one or more
-- contributor license agreements.  See the NOTICE file distributed with
-- this work for additional information regarding copyright ownership.
-- The ASF licenses this file to You under the Apache License, Version 2.0
-- (the "License"); you may not use this file except in compliance with
-- the License.  You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

set mapred.job.tracker=localhost:9001;
set hive.metastore.warehouse.dir=hdfs://localhost:9000/user/hive/warehouse;

add jar file:///Users/amccurry/Development/incubator-blur/contrib/blur-hive/target/blur-hive-0.2.4-incubating-SNAPSHOT-hadoop1.jar;

add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/blur-console-0.2.4-incubating-SNAPSHOT-hadoop1-webapp.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/blur-core-0.2.4-incubating-SNAPSHOT-hadoop1.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/blur-gui-0.2.4-incubating-SNAPSHOT-hadoop1.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/blur-gui-0.2.4-incubating-SNAPSHOT-hadoop1.war;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/blur-mapred-hadoop1-0.2.4-incubating-SNAPSHOT-hadoop1.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/blur-query-0.2.4-incubating-SNAPSHOT-hadoop1.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/blur-shell-0.2.4-incubating-SNAPSHOT-hadoop1.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/blur-store-0.2.4-incubating-SNAPSHOT-hadoop1.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/blur-thrift-0.2.4-incubating-SNAPSHOT-hadoop1.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/blur-util-0.2.4-incubating-SNAPSHOT-hadoop1.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/commons-cli-1.2.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/concurrentlinkedhashmap-lru-1.3.2.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/guava-14.0.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/jackson-annotations-2.1.1.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/jackson-core-2.1.1.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/jackson-databind-2.1.1.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/jline-2.10.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/json-20090211.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/lucene-analyzers-common-4.3.0.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/lucene-codecs-4.3.0.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/lucene-core-4.3.0.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/lucene-highlighter-4.3.0.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/lucene-memory-4.3.0.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/lucene-queries-4.3.0.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/lucene-queryparser-4.3.0.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/lucene-sandbox-4.3.0.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/lucene-spatial-4.3.0.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/metrics-core-2.2.0.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/metrics-ganglia-2.2.0.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/metrics-graphite-2.2.0.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/metrics-servlet-2.2.0.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/spatial4j-0.3.jar;
add jar /Users/amccurry/Development/incubator-blur/distribution/target/apache-blur-0.2.4-incubating-SNAPSHOT-hadoop1-bin/lib/zookeeper-3.4.5.jar;

-- create database test;
use test;

--  CREATE TABLE test
--  ROW FORMAT SERDE 'org.apache.blur.hive.BlurSerDe'
--  WITH SERDEPROPERTIES (
--    'blur.zookeeper.connection'='localhost',
--    'blur.table'='test_hdfs',
--    'blur.family'='fam0'
--  )
-- STORED BY 'org.apache.blur.hive.BlurHiveStorageHandler';

desc test;

-- create table input_data (
-- rowid string,
-- recordid string,
-- col0 string,
-- col1 string,
-- col2 string,
-- col3 string,
-- col4 string,
-- col5 string,
-- col6 string,
-- col7 string,
-- col8 string,
-- col9 string
-- );

select * from input_data;

insert overwrite table test select * from input_data distribute by rowid;



