require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

desc 'Default: run unit tests.'
task :default => :test

desc 'Test afs gem.'
Rake::TestTask.new(:test) do |t|
  t.libs << 'lib' << 'test'
  t.pattern = 'test/**/*_test.rb'
  t.verbose = true
end

desc 'Generate documentation for afs gem.'
Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title = 'Afs'
  rdoc.options << '--line-numbers' << '--inline-source'
  rdoc.rdoc_files.include('README.md')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

begin
  require "jeweler"
  require "./lib/afs/version"
  Jeweler::Tasks.new do |gem|
    gem.name = "afs"
    gem.version = Afs::VERSION
    gem.summary = gem.description = "Abstract Filesystem Engine for Rails 3"
    gem.email = 'crohr@nearinfinity.com'
    gem.homepage = 'TODO'
    gem.authors = ['Chris Rohr']
    gem.files = FileList["[A-Z]*", "{app,config,lib}/**/*", 'init.rb']
    
    #TODO: Add Runtime dependencies here
    
    #TODO: Add Development dependencies here
  end
  Jeweler::GemcutterTasks.new
rescue LoadError => le
  puts "Jeweler not available. Install it for jeweler-related tasks with: gem install jeweler: #{le.message}"
end
