source 'http://rubygems.org'

gem 'rails', '3.0.7'

gem 'sqlite3'
gem 'jquery-rails', '>= 0.2.6'
gem 'compass'
gem 'haml'
gem 'barista'
gem 'thrift'

group :development, :test do
	gem 'autotest'
	gem 'rspec-rails'
end

