source 'http://rubygems.org'

gem 'rails', '3.0.7'

gem 'sqlite3'
gem 'mysql'
gem 'jquery-rails', '>= 0.2.6'
gem 'compass'
gem 'haml'
gem 'barista'
gem 'thrift_client'
gem 'authlogic'
gem 'cancan', :git => 'git://github.com/ryanb/cancan.git', :branch => '2.0'
gem 'role_model'

gem 'capistrano'

group :development, :test do
	gem 'autotest'
	gem 'rspec-rails'
	gem 'ci_reporter'
	gem 'metric_fu'
	gem 'cover_me'
  gem 'nifty-generators'
  gem 'rails-erd'
  gem 'factory_girl_rails'
end
