source 'https://rubygems.org'

gem 'rails', '3.2.2'

gem 'mysql2'
gem 'jquery-rails'
gem 'thrift_client'
gem 'authlogic'
gem 'cancan', '2.0.0.alpha', :path => 'vendor/gems/cancan'
gem 'twitter_bootstrap_form_for'
gem 'bootstrap-sass'
gem 'js-routes'
gem 'haml-rails'
gem 'sass-rails',   '~> 3.2.3'
gem 'ejs'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'ci_reporter'
  gem 'rails-erd'
  gem 'factory_girl_rails'
  gem 'launchy'
  gem 'thin'
  gem 'debugger'
end

group :test do
  gem 'simplecov', :require => false
end

