# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'rake'
require 'ci/reporter/rake/rspec'
require 'metric_fu'

module ::BlurAdmin
  class Application
    include Rake::DSL
  end
end

module ::RakeFileUtils
  extend Rake::FileUtilsExt
end

MetricFu::Configuration.run do |config|
  config.metrics = [:stats, :flog, :flay, :reek, :roodi, :rails_best_practices, :hotspots]
  config.flog    = { :dirs_to_flog => ['app'] }
  config.reek    = { :dirs_to_reek => ['app'] }
  config.roodi   = { :dirs_to_roodi => ['app'] }
end

BlurAdmin::Application.load_tasks
