require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HdfsMetricsController do

  # This should return the minimal set of attributes required to create a valid
  # HdfsMetric. As you add validations to HdfsMetric, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HdfsMetricsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all hdfs_metrics as @hdfs_metrics" do
      hdfs_metric = HdfsMetric.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hdfs_metrics).should eq([hdfs_metric])
    end
  end

  describe "GET show" do
    it "assigns the requested hdfs_metric as @hdfs_metric" do
      hdfs_metric = HdfsMetric.create! valid_attributes
      get :show, {:id => hdfs_metric.to_param}, valid_session
      assigns(:hdfs_metric).should eq(hdfs_metric)
    end
  end

  describe "GET new" do
    it "assigns a new hdfs_metric as @hdfs_metric" do
      get :new, {}, valid_session
      assigns(:hdfs_metric).should be_a_new(HdfsMetric)
    end
  end

  describe "GET edit" do
    it "assigns the requested hdfs_metric as @hdfs_metric" do
      hdfs_metric = HdfsMetric.create! valid_attributes
      get :edit, {:id => hdfs_metric.to_param}, valid_session
      assigns(:hdfs_metric).should eq(hdfs_metric)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HdfsMetric" do
        expect {
          post :create, {:hdfs_metric => valid_attributes}, valid_session
        }.to change(HdfsMetric, :count).by(1)
      end

      it "assigns a newly created hdfs_metric as @hdfs_metric" do
        post :create, {:hdfs_metric => valid_attributes}, valid_session
        assigns(:hdfs_metric).should be_a(HdfsMetric)
        assigns(:hdfs_metric).should be_persisted
      end

      it "redirects to the created hdfs_metric" do
        post :create, {:hdfs_metric => valid_attributes}, valid_session
        response.should redirect_to(HdfsMetric.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hdfs_metric as @hdfs_metric" do
        # Trigger the behavior that occurs when invalid params are submitted
        HdfsMetric.any_instance.stub(:save).and_return(false)
        post :create, {:hdfs_metric => {}}, valid_session
        assigns(:hdfs_metric).should be_a_new(HdfsMetric)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HdfsMetric.any_instance.stub(:save).and_return(false)
        post :create, {:hdfs_metric => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hdfs_metric" do
        hdfs_metric = HdfsMetric.create! valid_attributes
        # Assuming there are no other hdfs_metrics in the database, this
        # specifies that the HdfsMetric created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HdfsMetric.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => hdfs_metric.to_param, :hdfs_metric => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested hdfs_metric as @hdfs_metric" do
        hdfs_metric = HdfsMetric.create! valid_attributes
        put :update, {:id => hdfs_metric.to_param, :hdfs_metric => valid_attributes}, valid_session
        assigns(:hdfs_metric).should eq(hdfs_metric)
      end

      it "redirects to the hdfs_metric" do
        hdfs_metric = HdfsMetric.create! valid_attributes
        put :update, {:id => hdfs_metric.to_param, :hdfs_metric => valid_attributes}, valid_session
        response.should redirect_to(hdfs_metric)
      end
    end

    describe "with invalid params" do
      it "assigns the hdfs_metric as @hdfs_metric" do
        hdfs_metric = HdfsMetric.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HdfsMetric.any_instance.stub(:save).and_return(false)
        put :update, {:id => hdfs_metric.to_param, :hdfs_metric => {}}, valid_session
        assigns(:hdfs_metric).should eq(hdfs_metric)
      end

      it "re-renders the 'edit' template" do
        hdfs_metric = HdfsMetric.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HdfsMetric.any_instance.stub(:save).and_return(false)
        put :update, {:id => hdfs_metric.to_param, :hdfs_metric => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hdfs_metric" do
      hdfs_metric = HdfsMetric.create! valid_attributes
      expect {
        delete :destroy, {:id => hdfs_metric.to_param}, valid_session
      }.to change(HdfsMetric, :count).by(-1)
    end

    it "redirects to the hdfs_metrics list" do
      hdfs_metric = HdfsMetric.create! valid_attributes
      delete :destroy, {:id => hdfs_metric.to_param}, valid_session
      response.should redirect_to(hdfs_metrics_url)
    end
  end

end
