source 'https://rubygems.org'

gem 'rails', '3.2.2'

gem 'mysql2'
gem 'jquery-rails'
gem 'thrift_client'
gem 'authlogic'
gem 'cancan', '2.0.0.alpha', :path => 'vendor/gems/cancan'
gem 'twitter_bootstrap_form_for'
gem 'bootstrap-sass'
gem 'js-routes'
gem 'haml-rails'
gem 'sass-rails',   '~> 3.2.3'
